### ISSUE TITLE
Fishfarm in Tainan

### ISSUE THREAD

**Issue by neil33533** [hotosm/oam-uploader-admin#58] opened 2017-05-07 02:13 UTC
Name: Modou Fishfarm
Email: neil33533@gmail.com
Location of imagery: Taiwan
Source of imagery: Tainan Community College
Short description of collection: Pollutant fishfarms in Taiwan
Have you received approval for making this imagery available (yes/no)?: yes

**Comment by smit1678** [comment] 2017-05-07 03:00
A duplicate of #59.

**Closed by smit1678** 2017-05-07 03:00 UTC
